### ISSUE TITLE
Method to get selected Tree Node

### ISSUE THREAD

**Issue by dhirajsonavane** [tonyhallett/useSeparateToggleClick#19]
Hi, 

I am trying to use your plugin and works great but just wondering if there is any method to get selected tree node id or name when click on it? I am talking about 'Fussy expansion' and 'Icon toggle expansion' examples.

My scenario is - 

I am using tree view in the popover simulating dropdown behavior. I want to select tree node and close the popover. But, when click on arrows, I want to keep it open. I also want to get selected tree node when click on text so that I can query api.

**Comment by tonyhallett** [comment]
Hi.  Sorry but I wrote this years ago.  Look at the source and adapt as required.
